package com.Nxer.TwistSpaceTechnology.common.material;

import static gregtech.api.enums.OrePrefixes.nanite;

import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashSet;

import goodgenerator.util.CharExchanger;
import gregtech.api.enums.Dyes;
import gregtech.api.enums.Element;
import gregtech.api.enums.Materials;
import gregtech.api.enums.SubTag;
import gregtech.api.enums.TCAspects;
import gregtech.api.enums.TextureSet;
import gregtech.common.render.items.InfinityRenderer;

/**
 * Register new materials here by GregTech Material System
 */
public class MaterialsTST {

    public static final Materials NeutroniumAlloy = new Materials(
        "Neutronium Alloy",
        "NeutroniumAlloy",
        null,
        "Nt\u2087Du\u2082Fl҉?",
        "flavorText",
        false,
        TextureSet.SET_SHINY,
        Dyes._NULL,
        0x00D9DCCB,
        0x00D9DCCB,
        98304000,
        18,
        32.0F,
        null,
        0,
        null,
        0,
        1,
        1,
        1,
        -1,
        -1,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        0,
        false,
        1,
        12000,
        12500,
        true,
        false,
        false,
        false,
        1,
        1,
        2,
        Collections.emptyList(),
        Arrays.asList(
            new TCAspects.TC_AspectStack(TCAspects.ORDO, 1),
            new TCAspects.TC_AspectStack(TCAspects.ALIENIS, 2),
            new TCAspects.TC_AspectStack(TCAspects.PERDITIO, 3),
            new TCAspects.TC_AspectStack(TCAspects.METALLUM, 5)),
        Collections.emptyList(),
        null,
        null,
        null,
        null,
        new LinkedHashSet<>(Arrays.asList(SubTag.METAL))) {};

    public static final Materials AxonisAlloy = new Materials(
        "Axonis Alloy",
        "AxonisAlloy",
        null,
        "۞\u2085(Hy⚶)\u2083⸎\u2082(IcMa)TbSh" + CharExchanger.shifter(9191),
        "flavorText",
        false,
        TextureSet.SET_SHINY,
        Dyes._NULL,
        0x00C54324,
        0x00C54324,
        98304000,
        18,
        96.0F,
        null,
        0,
        null,
        0,
        1,
        1,
        1,
        -1,
        -1,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        0,
        false,
        1,
        13000,
        13200,
        true,
        false,
        true,
        false,
        1,
        1,
        2,
        Collections.emptyList(),
        Arrays.asList(
            new TCAspects.TC_AspectStack(TCAspects.SENSUS, 1),
            new TCAspects.TC_AspectStack(TCAspects.PRAECANTATIO, 2),
            new TCAspects.TC_AspectStack(TCAspects.METALLUM, 4)),
        Collections.emptyList(),
        null,
        null,
        null,
        null,
        new LinkedHashSet<>(Arrays.asList(SubTag.METAL))) {};

    public static final Materials Axonium = new Materials(
        "Axonium",
        "Axonium",
        null,
        "A☀",
        "flavorText",
        false,
        TextureSet.SET_SHINY,
        Dyes._NULL,
        0x00F32D1B,
        0x00F32D1B,
        1048576000,
        24,
        480.0F,
        null,
        0,
        null,
        0,
        1,
        1,
        1,
        -1,
        -1,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        0,
        false,
        1,
        23000,
        26000,
        true,
        false,
        false,
        false,
        1,
        1,
        2,
        Collections.emptyList(),
        Arrays.asList(
            new TCAspects.TC_AspectStack(TCAspects.SENSUS, 1),
            new TCAspects.TC_AspectStack(TCAspects.PRAECANTATIO, 2),
            new TCAspects.TC_AspectStack(TCAspects.VICTUS, 3),
            new TCAspects.TC_AspectStack(TCAspects.METALLUM, 5)),
        Collections.emptyList(),
        null,
        null,
        null,
        null,
        new LinkedHashSet<>(Arrays.asList(SubTag.METAL))) {};

    public static final Materials Dubnium = new Materials(
        "Dubnium",
        "Dubnium",
        Element.Db,
        "",
        "flavorText",
        false,
        TextureSet.SET_METALLIC,
        Dyes._NULL,
        0x00C8C8C8,
        0x00C8C8C8,
        0,
        2,
        1.0F,
        null,
        0,
        null,
        0,
        1,
        1,
        1,
        -1,
        -1,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        0,
        false,
        1,
        3231,
        3231,
        false,
        false,
        false,
        false,
        1,
        1,
        2,
        Collections.emptyList(),
        Arrays.asList(
            new TCAspects.TC_AspectStack(TCAspects.RADIO, 5),
            new TCAspects.TC_AspectStack(TCAspects.METALLUM, 3)),
        Collections.emptyList(),
        null,
        null,
        null,
        null,
        new LinkedHashSet<>(Arrays.asList(SubTag.METAL))) {};

    // Register extra information
    static {
        nanite.mGeneratedItems.add(Materials.CosmicNeutronium);
        nanite.mGeneratedItems.add(MaterialsTST.Axonium);
    }

    public static void initClient() {
        Axonium.renderer = new InfinityRenderer();
    }

    public static void init() {
        // to load this class
    }

}
