package com.Nxer.TwistSpaceTechnology.common.material;

import static gregtech.api.enums.OrePrefixes.nanite;

import goodgenerator.util.CharExchanger;
import gregtech.api.enums.Dyes;
import gregtech.api.enums.Element;
import gregtech.api.enums.MaterialBuilder;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.SubTag;
import gregtech.api.enums.TCAspects;
import gregtech.api.enums.TextureSet;
import gregtech.api.enums.TierEU;
import gregtech.common.render.items.InfinityRenderer;

/**
 * Register new material here by Gregtech Material System
 */
public class MaterialsTST {

    public static Materials NeutroniumAlloy;
    public static Materials AxonisAlloy;
    public static Materials Axonium;
    public static Materials Dubnium;

    static {
        MaterialsTST.init();
    }

    private static void loadMaterials() {
        MaterialsTST.NeutroniumAlloy = loadNeutroniumAlloy();
        MaterialsTST.AxonisAlloy = loadAxonisAlloy();
        MaterialsTST.Axonium = loadAxonium();
        MaterialsTST.Dubnium = loadDubnium();
    }

    private static Materials loadNeutroniumAlloy() {
        return new MaterialBuilder().setName("NeutroniumAlloy")
            .setDefaultLocalName("Neutronium Alloy")
            .setChemicalFormula("\"Nt\\u2087Du\\u2082Fl҉?\"")
            .setARGB(0x00D9DCCB)
            .setIconSet(TextureSet.SET_SHINY)
            .setMeltingPoint(12000)
            .setBlastFurnaceTemp(12500)
            .setTool(98304000, 18, 32F)
            .setBlastFurnaceRequired(true)
            .setDensity(1, 1)
            .addDustItems()
            .addMetalItems()
            .addToolHeadItems()
            .addGearItems()
            .setElement(Element.Db)
            .addSubTag(SubTag.METAL)
            .setColor(Dyes._NULL)
            .addAspect(TCAspects.ORDO, 1)
            .addAspect(TCAspects.ALIENIS, 2)
            .addAspect(TCAspects.PERDITIO, 3)
            .addAspect(TCAspects.METALLUM, 5)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedVacuumFreezerRecipe(false)
            .addFluid()
            .constructMaterial()
            .setProcessingMaterialTierEU(TierEU.RECIPE_UEV);
    }

    private static Materials loadAxonisAlloy() {
        return new MaterialBuilder().setName("AxonisAlloy")
            .setDefaultLocalName("Axonis Alloy")
            .setChemicalFormula("۞\u2085(Hy⚶)\u2083⸎\u2082(IcMa)TbSh" + CharExchanger.shifter(9191))
            .setARGB(0xC54324)
            .setIconSet(TextureSet.SET_SHINY)
            .setMeltingPoint(13000)
            .setBlastFurnaceTemp(13200)
            .setTool(98304000, 18, 32F)
            .setBlastFurnaceRequired(true)
            .setDensity(2, 1)
            .addDustItems()
            .addMetalItems()
            .addFluid()
            .addToolHeadItems()
            .addGearItems()
            .addSubTag(SubTag.METAL)
            .setColor(Dyes._NULL)
            .addAspect(TCAspects.SENSUS, 1)
            .addAspect(TCAspects.PRAECANTATIO, 2)
            .addAspect(TCAspects.METALLUM, 4)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedVacuumFreezerRecipe(false)
            .constructMaterial()
            .setProcessingMaterialTierEU(TierEU.RECIPE_UIV);
    }

    private static Materials loadAxonium() {
        return new MaterialBuilder().setName("Axonium")
            .setDefaultLocalName("Axonium")
            .setChemicalFormula("A☀")
            .setARGB(0xF32D1B)
            .setIconSet(TextureSet.SET_SHINY)
            .setMeltingPoint(23000)
            .setBlastFurnaceTemp(26000)
            .setTool(1048576000, 24, 32F)
            .setBlastFurnaceRequired(true)
            .setDensity(2, 1)
            .addDustItems()
            .addMetalItems()
            .addToolHeadItems()
            .addGearItems()
            .addPlasma()
            .addFluid()
            .addOrePrefix(OrePrefixes.nanite)
            .addSubTag(SubTag.METAL)
            .setColor(Dyes._NULL)
            .addAspect(TCAspects.SENSUS, 1)
            .addAspect(TCAspects.PRAECANTATIO, 2)
            .addAspect(TCAspects.VICTUS, 3)
            .addAspect(TCAspects.METALLUM, 5)
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedVacuumFreezerRecipe(false)
            .constructMaterial()
            .setProcessingMaterialTierEU(TierEU.RECIPE_UMV);
    }

    private static Materials loadDubnium() {
        return new MaterialBuilder().setName("Dubnium")
            .setDefaultLocalName("Dubnium")
            .setARGB(0xC8C8C8)
            .setIconSet(TextureSet.SET_METALLIC)
            .setMeltingPoint(3231)
            .setBlastFurnaceTemp(3231)
            .setTool(0, 2, 1F)
            .setBlastFurnaceRequired(false)
            .setDensity(2, 1)
            .addDustItems()
            .addMetalItems()
            .addToolHeadItems()
            .addGearItems()
            .addFluid()
            .setColor(Dyes._NULL)
            .addAspect(TCAspects.RADIO, 5)
            .addAspect(TCAspects.METALLUM, 3)
            .addPlasma()
            .setAutoGenerateBlastFurnaceRecipes(false)
            .setAutoGeneratedVacuumFreezerRecipe(false)
            .constructMaterial()
            .setProcessingMaterialTierEU(TierEU.RECIPE_LV);
    }

    // register Extra Information
    static {

        nanite.mGeneratedItems.add(Materials.CosmicNeutronium);
    }

    public static void initClient() {
        Axonium.renderer = new InfinityRenderer();
    }

    public static void init() {
        loadMaterials();
        new MaterialsIDMap().register();
    }
}
